spring:
  mail:
    host: smtp.163.com
    username: fangjun0624@163.com
    password: a123456
    default-encoding: UTF-8

#发送者的邮箱地址
email.from: fangjun0624@163.com
#接受者的邮箱地址
email.to: fangjun@wanwaytech.com
